# Generated by Django 5.2.17 on 2026-09-17 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAppliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('appliance_type', models.CharField(max_length=100)),
                ('rated_power_watts', models.FloatField(default=100.0)),
                ('power_category', models.CharField(choices=[('low', 'Low Power'), ('moderate', 'Moderate Power'), ('high', 'High Power')], default='low', max_length=20)),
                ('icon_key', models.CharField(default='zap', max_length=50)),
                ('iot_enabled', models.BooleanField(default=False)),
                ('iot_device_name', models.CharField(blank=True, max_length=100, null=True)),
                ('iot_status', models.CharField(default='Not Connected', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
