# Generated by Django 5.2.17 on 2026-09-17 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userappliance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='REFITHousehold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.IntegerField(unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('data_file', models.CharField(max_length=100)),
                ('data_source', models.CharField(default='refit', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refit_household', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
