# Generated by Django 5.2.17 on 2026-09-17 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_refithousehold'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userappliance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_appliances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='REFITHousehold',
        ),
    ]
