# Generated by Django 5.2.17 on 2026-09-17 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_userappliance_user_refithousehold'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userappliance',
            name='auto_turn_off_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userappliance',
            name='power_state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userappliance',
            name='usage_limit_watts',
            field=models.FloatField(blank=True, default=2000.0, null=True),
        ),
        migrations.CreateModel(
            name='ApplianceControlSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliance_id', models.CharField(max_length=100)),
                ('power_state', models.BooleanField(default=True)),
                ('auto_turn_off_enabled', models.BooleanField(default=False)),
                ('usage_limit_watts', models.FloatField(blank=True, default=2000.0, null=True)),
                ('usage_limit_kwh', models.FloatField(blank=True, default=5.0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliance_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'appliance_id')},
            },
        ),
    ]
